### ISSUE TITLE
current code fails tests

### ISSUE THREAD

**Issue by DShumkov** [emmanuelroecker/php-w3cvalidator#1]
1) GlValidator\Tests\GlValidatorTest::testHtml
/Users/*******/prjs/custom-packages/php-w3cvalidator/tests/expected/test1/w3c_html_index.html different to /Users/********/prjs/custom-packages/php-w3cvalidator/tests/result/test1/w3c_html_index.html
Failed asserting that two strings are equal.
--- Expected
+++ Actual
2) GlValidator\Tests\GlValidatorTest::testHtmlCss
/Users/**********/prjs/custom-packages/php-w3cvalidator/tests/expected/test1/w3c_html_index.html different /Users/********/prjs/custom-packages/php-w3cvalidator/tests/result/test1/w3c_html_index.html
Failed asserting that two strings are equal.
--- Expected
+++ Actual

**Comment by emmanuelroecker** [comment]
Hi,

It's ok for me.

Can you send me your files ***/result/test1/w3c_html_index.html and ***/result/test1/w3c_html_index.html ?

Best regards

**Comment by DShumkov** [comment]
Hi
Sorry for delay.
Please find enclosed file.

**Comment by DShumkov** [comment]
Ahh ok I can't add html or txt file sorry.

<!DOCTYPE html><html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><link href="icon.png" rel="icon"/><link href="style.css" rel="stylesheet"/><title>Showing results for uploaded file index.html - Nu Html Checker</title><meta name="viewport" content="width=device-width, initial-scale=1"/><style type="text/css" media="all">@import url("https://validator.w3.org/nu/style.css");</style></head><body><h2>test1/index.html</h2><ol><li class="info"><p><strong>Info</strong>: <span>The Content-Type was <code>text/html</code>. Using the HTML parser.</span></p></li><li class="info"><p><strong>Info</strong>: <span>Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.</span></p></li></ol><p class="success">The document validates according to the specified schema(s) and to additional constraints checked by the validator.</p></body></html>

**Comment by emmanuelroecker** [comment]
Hi
Finally, with a little delay, I fixed it. 
You can see the "Travis CI" badge in readme. ;)
